Refactored out $HASHICORP_RELEASES env var

diff --git a/0.X/Dockerfile b/0.X/Dockerfile
--- a/0.X/Dockerfile
+++ b/0.X/Dockerfile
@@ -4,9 +4,6 @@ MAINTAINER Preetha Appan <preetha@hashicorp.com> (@preetapan)
 # This is the release of Consul to pull in.
 ENV CONSUL_VERSION=1.2.3
 
-# This is the location of the releases.
-ENV HASHICORP_RELEASES=https://releases.hashicorp.com
-
 # Create a consul user and group first so the IDs get set the same way, even as
 # the rest of this may change over time.
 RUN addgroup consul && \
@@ -24,11 +21,11 @@ RUN set -eux && \
         armhf) consulArch='arm' ;; \
         x86) consulArch='386' ;; \
         x86_64) consulArch='amd64' ;; \
-        *) echo >&2 "error: unsupported architecture: ${apkArch} (see ${HASHICORP_RELEASES}/consul/${CONSUL_VERSION}/)" && exit 1 ;; \
+        *) echo >&2 "error: unsupported architecture: ${apkArch} (see https://releases.hashicorp.com/consul/${CONSUL_VERSION}/)" && exit 1 ;; \
     esac && \
-    wget ${HASHICORP_RELEASES}/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_${consulArch}.zip && \
-    wget ${HASHICORP_RELEASES}/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_SHA256SUMS && \
-    wget ${HASHICORP_RELEASES}/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_SHA256SUMS.sig && \
+    wget https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_${consulArch}.zip && \
+    wget https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_SHA256SUMS && \
+    wget https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_SHA256SUMS.sig && \
     gpg --batch --verify consul_${CONSUL_VERSION}_SHA256SUMS.sig consul_${CONSUL_VERSION}_SHA256SUMS && \
     grep consul_${CONSUL_VERSION}_linux_${consulArch}.zip consul_${CONSUL_VERSION}_SHA256SUMS | sha256sum -c && \
     unzip -d /bin consul_${CONSUL_VERSION}_linux_${consulArch}.zip && \
